.TH KVPM "1" "March 2012" KDE "KDE Application"
.SH NAME
kvpm \- Graphical user interface for LVM based on KDE
.SH SYNOPSIS
.B kvpm
[\fIQt-options\fR] [\fIKDE-options\fR]
.SH DESCRIPTION
This manual page briefly documents the
.B KVPM
KDE Application.
.P
.B KVPM
is a graphical user interface for the Linux Volume Manager (LVM) and 
libparted.  It uses the standard LVM tools and programs to manipulate logical
volumes, such as resizing, deleting or creating them. It can also format 
volumes and mount or unmount them. Creating, deleting and resizing partitions
is also supported.
.SS "Generic options:"
.TP
\fB\-\-help\fR
Show help about options
.TP
\fB\-\-help\-qt\fR
Show Qt specific options
.TP
\fB\-\-help\-kde\fR
Show KDE specific options
.TP
\fB\-\-help\-all\fR
Show all options
.TP
\fB\-\-author\fR
Show author information
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version information
.TP
\fB\-\-license\fR
Show license information
.TP
\fB\-\-\fR
End of options
.SH SEE ALSO
Full user documentation is available through the KDE Help Center.  You can also enter the URL
.BR help:/kvpm/
directly into konqueror or you can run 
.BR "`khelpcenter help:/kvpm/'"
from the command-line.
.br
.SH AUTHOR
KVPM is copyright by
.nh
Benjamin Scott <benscott@nwlink.com>
.hy
.br

